/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustScoreRouteImport } from './routes/trust-score'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LivenessRouteImport } from './routes/liveness'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TrustScoreRoute = TrustScoreRouteImport.update({
  id: '/trust-score',
  path: '/trust-score',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LivenessRoute = LivenessRouteImport.update({
  id: '/liveness',
  path: '/liveness',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/home': typeof HomeRoute
  '/liveness': typeof LivenessRoute
  '/login': typeof LoginRoute
  '/queue': typeof QueueRoute
  '/scan': typeof ScanRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/trust-score': typeof TrustScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/home': typeof HomeRoute
  '/liveness': typeof LivenessRoute
  '/login': typeof LoginRoute
  '/queue': typeof QueueRoute
  '/scan': typeof ScanRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/trust-score': typeof TrustScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/home': typeof HomeRoute
  '/liveness': typeof LivenessRoute
  '/login': typeof LoginRoute
  '/queue': typeof QueueRoute
  '/scan': typeof ScanRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/trust-score': typeof TrustScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/home'
    | '/liveness'
    | '/login'
    | '/queue'
    | '/scan'
    | '/security'
    | '/settings'
    | '/success'
    | '/trust-score'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/home'
    | '/liveness'
    | '/login'
    | '/queue'
    | '/scan'
    | '/security'
    | '/settings'
    | '/success'
    | '/trust-score'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/home'
    | '/liveness'
    | '/login'
    | '/queue'
    | '/scan'
    | '/security'
    | '/settings'
    | '/success'
    | '/trust-score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  HomeRoute: typeof HomeRoute
  LivenessRoute: typeof LivenessRoute
  LoginRoute: typeof LoginRoute
  QueueRoute: typeof QueueRoute
  ScanRoute: typeof ScanRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SuccessRoute: typeof SuccessRoute
  TrustScoreRoute: typeof TrustScoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-score': {
      id: '/trust-score'
      path: '/trust-score'
      fullPath: '/trust-score'
      preLoaderRoute: typeof TrustScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liveness': {
      id: '/liveness'
      path: '/liveness'
      fullPath: '/liveness'
      preLoaderRoute: typeof LivenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  HomeRoute: HomeRoute,
  LivenessRoute: LivenessRoute,
  LoginRoute: LoginRoute,
  QueueRoute: QueueRoute,
  ScanRoute: ScanRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SuccessRoute: SuccessRoute,
  TrustScoreRoute: TrustScoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
